version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: ${DB_HOST}
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    
  api:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    env_file:
      - ./.env


